version: '3.7'

services:

  sample:
    stdin_open: true
    tty: true 
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"